SIM=icarus
COCOTB_REDUCED_LOG_FMT=1
VERILOG_SOURCES = $(PWD)/../src/button_deb.v
TOPLEVEL=button_deb
MODULE=test_$(TOPLEVEL)
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
